name: Notify Completion

on:
  workflow_run:
    workflows: ["Build and Test Maven Project"]
    types:
      - completed

jobs:
  notify:
    runs-on: ubuntu-latest
    
    steps:
    - name: Notify completion
      run: |
        curl -X POST https://eshonkulov-asliddin.jprq.live/workflow/results \
          -H "Content-Type: application/json" \
          -d '{
            "status": "completed",
            "repository": {
              "name": "${{ github.repository }}",
              "owner": "${{ github.repository_owner }}"
            },
            "branch": "${{ github.ref_name }}",
            "commit": "${{ github.sha }}",
            "runId": "${{ github.event.workflow_run.id }}",
            "runNumber": "${{ github.event.workflow_run.run_number }}"
          }'

